php = require 'phpjs'

exports.bool = (value) ->
	if !value
		return false
	
	return true

exports.game_type = (value) ->
	switch value
		when 0x01 then value = 'Ladder 1vs1/FFA'
		when 0x09 then value = 'Custom game'
		when 0x0D then value = 'Single player/Local game'
		when 0x20 then value = 'Ladder team game (AT/RT)'
		else value = 'unknown'
	
	return value

exports.race = (value) ->
	switch value
		when 'hpea', 0x01, 0x41 then value = 'Human'
		when 'opeo', 0x02, 0x42 then value = 'Orc'
		when 'ewsp', 0x04, 0x44 then value = 'NightElf'
		when 'uaco', 0x08, 0x48 then value = 'Undead'
		when 0x20, 0x60 then value = 'Random'
		else value = 0 # do not change this line
	
	return value

exports.ai = (value) ->
	switch value
		when 0x00 then value = "Easy"
		when 0x01 then value = "Normal"
		when 0x02 then value = "Insane"
	
	return value

exports.select_mode = (value) ->
	switch value
		when 0x00 then value = "Team & race selectable"
		when 0x01 then value = "Team not selectable"
		when 0x03 then value = "Team & race not selectable"
		when 0x04 then value = "Race fixed to random"
		when 0xCC then value = "Automated Match Making (ladder)"
	
	return value

exports.chat_mode = (value, player) ->
	player = player || 'unknown'
	
	switch value
		when 0x00 then value = 'All'
		when 0x01 then value = 'Allies'
		when 0x02 then value = 'Observers'
		when 0xFE then value = 'The game has been paused by ' + player + '.'
		when 0xFF then value = 'The game has been resumed by ' + player + '.'
		else value -= 2 # this is for private messages
	
	return value

exports.itemid = (value) ->
	# ignore numeric Item IDs (0x41 - ASCII A, 0x7A - ASCII z)
	if (php.ord(value[0]) < 0x41 || php.ord(value[0]) > 0x7A)
		return 0
	
	# you can change the names but not the prefixes (h_, u_, a_, etc.)
	# Human
	else if (value[0] == 'h')
		switch value
			# units
			when 'hfoo' then value = 'u_Footman'
			when 'hkni' then value = 'u_Knight'
			when 'hmpr' then value = 'u_Priest'
			when 'hmtm' then value = 'u_Mortar Team'
			when 'hpea' then value = 'u_Peasant'
			when 'hrif' then value = 'u_Rifleman'
			when 'hsor' then value = 'u_Sorceress'
			when 'hmtt', 'hrtt' then value = 'u_Siege Engine'
			when 'hgry' then value = 'u_Gryphon Rider'
			when 'hgyr' then value = 'u_Flying Machine'
			when 'hspt' then value = 'u_Spell Breaker'
			when 'hdhw' then value = 'u_Dragonhawk Rider'
			# building upgrades
			when 'hkee' then value = 'b_Keep'
			when 'hcas' then value = 'b_Castle'
			when 'hctw' then value = 'b_Cannon Tower'
			when 'hgtw' then value = 'b_Guard Tower'
			when 'hatw' then value = 'b_Arcane Tower'

	# Night Elf
	else if (value[0] == 'e')
		switch value
			# units
			when 'ebal' then value = 'u_Glaive Thrower'
			when 'echm' then value = 'u_Chimaera'
			when 'edoc' then value = 'u_Druid of the Claw'
			when 'edot' then value = 'u_Druid of the Talon'
			when 'ewsp' then value = 'u_Wisp'
			when 'esen' then value = 'u_Huntress'
			when 'earc' then value = 'u_Archer'
			when 'edry' then value = 'u_Dryad'
			when 'ehip' then value = 'u_Hippogryph'
			when 'emtg' then value = 'u_Mountain Giant'
			when 'efdr' then value = 'u_Faerie Dragon'
			# building upgrades
			when 'etoa' then value = 'b_Tree of Ages'
			when 'etoe' then value = 'b_Tree of Eternity'

	# Orc
	else if (value[0] == 'o')
		switch value
			# units
			when 'ocat' then value = 'u_Demolisher'
			when 'odoc' then value = 'u_Troll Witch Doctor'
			when 'ogru' then value = 'u_Grunt'
			when 'ohun', 'otbk' then value = 'u_Troll Headhunter/Berserker'
			when 'okod' then value = 'u_Kodo Beast'
			when 'opeo' then value = 'u_Peon'
			when 'orai' then value = 'u_Raider'
			when 'oshm' then value = 'u_Shaman'
			when 'otau' then value = 'u_Tauren'
			when 'owyv' then value = 'u_Wind Rider'
			when 'ospw', 'ospm' then value = 'u_Spirit Walker'
			when 'otbr' then value = 'u_Troll Batrider'
			# building upgrades
			when 'ofrt' then value = 'b_Fortress'
			when 'ostr' then value = 'b_Stronghold'

	# Undead
	else if (value[0] == 'u')
		switch value
			# units
			when 'uaco' then value = 'u_Acolyte'
			when 'uabo' then value = 'u_Abomination'
			when 'uban' then value = 'u_Banshee'
			when 'ucry' then value = 'u_Crypt Fiend'
			when 'ufro' then value = 'u_Frost Wyrm'
			when 'ugar' then value = 'u_Gargoyle'
			when 'ugho' then value = 'u_Ghoul'
			when 'unec' then value = 'u_Necromancer'
			when 'umtw' then value = 'u_Meatwagon'
			when 'ushd' then value = 'u_Shade'
			when 'uobs' then value = 'u_Obsidian Statue'
			when 'ubsp' then value = 'u_Destroyer'
			# building upgrades
			when 'unp1' then value = 'b_Halls of the Dead'
			when 'unp2' then value = 'b_Black Citadel'
			when 'uzg1' then value = 'b_Spirit Tower'
			when 'uzg2' then value = 'b_Nerubian Tower'

	# Human heroes
	else if (value[0] == 'H')
		switch value
			when 'Hamg' then value = 'h_Archmage'
			when 'Hmkg' then value = 'h_Mountain King'
			when 'Hpal' then value = 'h_Paladin'
			when 'Hblm' then value = 'h_Blood Mage'

	# Night Elf heroes
	else if (value[0] == 'E')
		switch value
			when 'Edem' then value = 'h_Demon Hunter'
			when 'Ekee' then value = 'h_Keeper of the Grove'
			when 'Emoo' then value = 'h_Priestess of the Moon'
			when 'Ewar' then value = 'h_Warden'

	# Orc heroes
	else if (value[0] == 'O')
		switch value
			when 'Obla' then value = 'h_Blademaster'
			when 'Ofar' then value = 'h_Far Seer'
			when 'Otch' then value = 'h_Tauren Chieftain'
			when 'Oshd' then value = 'h_Shadow Hunter'

	# Undead heroes
	else if (value[0] == 'U')
		switch value
			when 'Udea' then value = 'h_Death Knight'
			when 'Udre' then value = 'h_DreadLord'
			when 'Ulic' then value = 'h_Lich'
			when 'Ucrl' then value = 'h_Crypt Lord'

	# neutral heroes
	else if (value[0] == 'N')
		switch value
			when 'Npbm' then value = 'h_Pandaren Brewmaster'
			when 'Nbrn' then value = 'h_Dark Ranger'
			when 'Nngs' then value = 'h_Naga Sea Witch'
			when 'Nplh' then value = 'h_Pit Lord'
			when 'Nbst' then value = 'h_Beastmaster'
			when 'Ntin' then value = 'h_Goblin Tinker'
			when 'Nfir' then value = 'h_FireLord'
			when 'Nalc' then value = 'h_Goblin Alchemist'

	# hero abilities
	# WARNING: the names of the heroes must be exactly the same as above
	else if (value[0] == 'A')
		switch value
			when 'AHbz' then value = 'a_Archmage:Blizzard'
			when 'AHwe' then value = 'a_Archmage:Summon Water Elemental'
			when 'AHab' then value = 'a_Archmage:Brilliance Aura'
			when 'AHmt' then value = 'a_Archmage:Mass Teleport'
			when 'AHtb' then value = 'a_Mountain King:Storm Bolt'
			when 'AHtc' then value = 'a_Mountain King:Thunder Clap'
			when 'AHbh' then value = 'a_Mountain King:Bash'
			when 'AHav' then value = 'a_Mountain King:Avatar'
			when 'AHhb' then value = 'a_Paladin:Holy Light'
			when 'AHds' then value = 'a_Paladin:Divine Shield'
			when 'AHad' then value = 'a_Paladin:Devotion Aura'
			when 'AHre' then value = 'a_Paladin:Resurrection'
			when 'AHdr' then value = 'a_Blood Mage:Siphon Mana'
			when 'AHfs' then value = 'a_Blood Mage:Flame Strike'
			when 'AHbn' then value = 'a_Blood Mage:Banish'
			when 'AHpx' then value = 'a_Blood Mage:Summon Phoenix'

			when 'AEmb' then value = 'a_Demon Hunter:Mana Burn'
			when 'AEim' then value = 'a_Demon Hunter:Immolation'
			when 'AEev' then value = 'a_Demon Hunter:Evasion'
			when 'AEme' then value = 'a_Demon Hunter:Metamorphosis'
			when 'AEer' then value = 'a_Keeper of the Grove:Entangling Roots'
			when 'AEfn' then value = 'a_Keeper of the Grove:Force of Nature'
			when 'AEah' then value = 'a_Keeper of the Grove:Thorns Aura'
			when 'AEtq' then value = 'a_Keeper of the Grove:Tranquility'
			when 'AEst' then value = 'a_Priestess of the Moon:Scout'
			when 'AHfa' then value = 'a_Priestess of the Moon:Searing Arrows'
			when 'AEar' then value = 'a_Priestess of the Moon:Trueshot Aura'
			when 'AEsf' then value = 'a_Priestess of the Moon:Starfall'
			when 'AEbl' then value = 'a_Warden:Blink'
			when 'AEfk' then value = 'a_Warden:Fan of Knives'
			when 'AEsh' then value = 'a_Warden:Shadow Strike'
			when 'AEsv' then value = 'a_Warden:Spirit of Vengeance'

			when 'AOwk' then value = 'a_Blademaster:Wind Walk'
			when 'AOmi' then value = 'a_Blademaster:Mirror Image'
			when 'AOcr' then value = 'a_Blademaster:Critical Strike'
			when 'AOww' then value = 'a_Blademaster:Bladestorm'
			when 'AOcl' then value = 'a_Far Seer:Chain Lighting'
			when 'AOfs' then value = 'a_Far Seer:Far Sight'
			when 'AOsf' then value = 'a_Far Seer:Feral Spirit'
			when 'AOeq' then value = 'a_Far Seer:Earth Quake'
			when 'AOsh' then value = 'a_Tauren Chieftain:Shockwave'
			when 'AOae' then value = 'a_Tauren Chieftain:Endurance Aura'
			when 'AOws' then value = 'a_Tauren Chieftain:War Stomp'
			when 'AOre' then value = 'a_Tauren Chieftain:Reincarnation'
			when 'AOhw' then value = 'a_Shadow Hunter:Healing Wave'
			when 'AOhx' then value = 'a_Shadow Hunter:Hex'
			when 'AOsw' then value = 'a_Shadow Hunter:Serpent Ward'
			when 'AOvd' then value = 'a_Shadow Hunter:Big Bad Voodoo'

			when 'AUdc' then value = 'a_Death Knight:Death Coil'
			when 'AUdp' then value = 'a_Death Knight:Death Pact'
			when 'AUau' then value = 'a_Death Knight:Unholy Aura'
			when 'AUan' then value = 'a_Death Knight:Animate Dead'
			when 'AUcs' then value = 'a_Dreadlord:Carrion Swarm'
			when 'AUsl' then value = 'a_Dreadlord:Sleep'
			when 'AUav' then value = 'a_Dreadlord:Vampiric Aura'
			when 'AUin' then value = 'a_Dreadlord:Inferno'
			when 'AUfn' then value = 'a_Lich:Frost Nova'
			when 'AUfa', 'AUfu' then value = 'a_Lich:Frost Armor'
			when 'AUdr' then value = 'a_Lich:Dark Ritual'
			when 'AUdd' then value = 'a_Lich:Death and Decay'
			when 'AUim' then value = 'a_Crypt lord:Impale'
			when 'AUts' then value = 'a_Crypt lord:Spiked Carapace'
			when 'AUcb' then value = 'a_Crypt lord:Carrion Beetles'
			when 'AUls' then value = 'a_Crypt lord:Locust Swarm'

			when 'ANbf' then value = 'a_Pandaren Brewmaster:Breath of Fire'
			when 'ANdb' then value = 'a_Pandaren Brewmaster:Drunken Brawler'
			when 'ANdh' then value = 'a_Pandaren Brewmaster:Drunken Haze'
			when 'ANef' then value = 'a_Pandaren Brewmaster:Storm Earth and Fire'
			when 'ANdr' then value = 'a_Dark Ranger:Life Drain'
			when 'ANsi' then value = 'a_Dark Ranger:Silence'
			when 'ANba' then value = 'a_Dark Ranger:Black Arrow'
			when 'ANch' then value = 'a_Dark Ranger:Charm'
			when 'ANms' then value = 'a_Naga Sea Witch:Mana Shield'
			when 'ANfa' then value = 'a_Naga Sea Witch:Frost Arrows'
			when 'ANfl' then value = 'a_Naga Sea Witch:Forked Lightning'
			when 'ANto' then value = 'a_Naga Sea Witch:Tornado'
			when 'ANrf' then value = 'a_Pit lord:Rain of Fire'
			when 'ANca' then value = 'a_Pit lord:Cleaving Attack'
			when 'ANht' then value = 'a_Pit lord:Howl of Terror'
			when 'ANdo' then value = 'a_Pit lord:Doom'
			when 'ANsg' then value = 'a_Beastmaster:Summon Bear'
			when 'ANsq' then value = 'a_Beastmaster:Summon Quilbeast'
			when 'ANsw' then value = 'a_Beastmaster:Summon Hawk'
			when 'ANst' then value = 'a_Beastmaster:Stampede'
			when 'ANeg' then value = 'a_Goblin Tinker:Engineering Upgrade'
			when 'ANcs', 'ANc1', 'ANc2', 'ANc3' then value = 'a_Goblin Tinker:Cluster Rockets'
			when 'ANsy', 'ANs1', 'ANs2', 'ANs3' then value = 'a_Goblin Tinker:Pocket Factory'
			when 'ANrg', 'ANg1', 'ANg2', 'ANg3' then value = 'a_Goblin Tinker:Robo-Goblin'
			when 'ANic', 'ANia' then value = 'a_Firelord:Incinerate'
			when 'ANso' then value = 'a_Firelord:Soul Burn'
			when 'ANlm' then value = 'a_Firelord:Summon Lava Spawn'
			when 'ANvc' then value = 'a_Firelord:Volcano'
			when 'ANhs' then value = 'a_Goblin Alchemist:Healing Spray'
			when 'ANab' then value = 'a_Goblin Alchemist:Acid Bomb'
			when 'ANcr' then value = 'a_Goblin Alchemist:Chemical Rage'
			when 'ANtm' then value = 'a_Goblin Alchemist:Transmute'

	# neutral units
	else if (value[0] == 'n')
		switch value
			when 'nskm' then value = 'u_Skeletal Marksman'
			when 'nskf' then value = 'u_Burning Archer'
			when 'nws1' then value = 'u_Dragon Hawk'
			when 'nban' then value = 'u_Bandit'
			when 'nrog' then value = 'u_Rogue'
			when 'nenf' then value = 'u_Enforcer'
			when 'nass' then value = 'u_Assassin'
			when 'nbdk' then value = 'u_Black Drake'
			when 'nrdk' then value = 'u_Red Dragon Whelp'
			when 'nbdr' then value = 'u_Black Dragon Whelp'
			when 'nrdr' then value = 'u_Red Drake'
			when 'nbwm' then value = 'u_Black Dragon'
			when 'nrwm' then value = 'u_Red Dragon'
			when 'nadr' then value = 'u_Blue Dragon'
			when 'nadw' then value = 'u_Blue Dragon Whelp'
			when 'nadk' then value = 'u_Blue Drake'
			when 'nbzd' then value = 'u_Bronze Dragon'
			when 'nbzk' then value = 'u_Bronze Drake'
			when 'nbzw' then value = 'u_Bronze Dragon Whelp'
			when 'ngrd' then value = 'u_Green Dragon'
			when 'ngdk' then value = 'u_Green Drake'
			when 'ngrw' then value = 'u_Green Dragon Whelp'
			when 'ncea' then value = 'u_Centaur Archer'
			when 'ncen' then value = 'u_Centaur Outrunner'
			when 'ncer' then value = 'u_Centaur Drudge'
			when 'ndth' then value = 'u_Dark Troll High Priest'
			when 'ndtp' then value = 'u_Dark Troll Shadow Priest'
			when 'ndtb' then value = 'u_Dark Troll Berserker'
			when 'ndtw' then value = 'u_Dark Troll WarLord'
			when 'ndtr' then value = 'u_Dark Troll'
			when 'ndtt' then value = 'u_Dark Troll Trapper'
			when 'nfsh' then value = 'u_Forest Troll High Priest'
			when 'nfsp' then value = 'u_Forest Troll Shadow Priest'
			when 'nftr' then value = 'u_Forest Troll'
			when 'nftb' then value = 'u_Forest Troll Berserker'
			when 'nftt' then value = 'u_Forest Troll Trapper'
			when 'nftk' then value = 'u_Forest Troll WarLord'
			when 'ngrk' then value = 'u_Mud Golem'
			when 'ngir' then value = 'u_Goblin Shredder'
			when 'nfrs' then value = 'u_Furbolg Shaman'
			when 'ngna' then value = 'u_Gnoll Poacher'
			when 'ngns' then value = 'u_Gnoll Assassin'
			when 'ngno' then value = 'u_Gnoll'
			when 'ngnb' then value = 'u_Gnoll Brute'
			when 'ngnw' then value = 'u_Gnoll Warden'
			when 'ngnv' then value = 'u_Gnoll Overseer'
			when 'ngsp' then value = 'u_Goblin Sapper'
			when 'nhrr' then value = 'u_Harpy Rogue'
			when 'nhrw' then value = 'u_Harpy Windwitch'
			when 'nits' then value = 'u_Ice Troll Berserker'
			when 'nitt' then value = 'u_Ice Troll Trapper'
			when 'nkob' then value = 'u_Kobold'
			when 'nkog' then value = 'u_Kobold Geomancer'
			when 'nthl' then value = 'u_Thunder Lizard'
			when 'nmfs' then value = 'u_Murloc Flesheater'
			when 'nmrr' then value = 'u_Murloc Huntsman'
			when 'nowb' then value = 'u_Wildkin'
			when 'nrzm' then value = 'u_Razormane Medicine Man'
			when 'nnwa' then value = 'u_Nerubian Warrior'
			when 'nnwl' then value = 'u_Nerubian Webspinner'
			when 'nogr' then value = 'u_Ogre Warrior'
			when 'nogm' then value = 'u_Ogre Mauler'
			when 'nogl' then value = 'u_Ogre Lord'
			when 'nomg' then value = 'u_Ogre Magi'
			when 'nrvs' then value = 'u_Frost Revenant'
			when 'nslf' then value = 'u_Sludge Flinger'
			when 'nsts' then value = 'u_Satyr Shadowdancer'
			when 'nstl' then value = 'u_Satyr Soulstealer'
			when 'nzep' then value = 'u_Goblin Zeppelin'
			when 'ntrt' then value = 'u_Giant Sea Turtle'
			when 'nlds' then value = 'u_Makrura Deepseer'
			when 'nlsn' then value = 'u_Makrura Snapper'
			when 'nmsn' then value = 'u_Mur\'gul Snarecaster'
			when 'nscb' then value = 'u_Spider Crab Shorecrawler'
			when 'nbot' then value = 'u_Transport Ship'
			when 'nsc2' then value = 'u_Spider Crab Limbripper'
			when 'nsc3' then value = 'u_Spider Crab Behemoth'
			when 'nbdm' then value = 'u_Blue Dragonspawn Meddler'
			when 'nmgw' then value = 'u_Magnataur Warrior'
			when 'nanb' then value = 'u_Barbed Arachnathid'
			when 'nanm' then value = 'u_Barbed Arachnathid'
			when 'nfps' then value = 'u_Polar Furbolg Shaman'
			when 'nmgv' then value = 'u_Magic Vault'
			when 'nitb' then value = 'u_Icy Treasure Box'
			when 'npfl' then value = 'u_Fel Beast'
			when 'ndrd' then value = 'u_Draenei Darkslayer'
			when 'ndrm' then value = 'u_Draenei Disciple'
			when 'nvdw' then value = 'u_Voidwalker'
			when 'nvdg' then value = 'u_Greater Voidwalker'
			when 'nnht' then value = 'u_Nether Dragon Hatchling'
			when 'nndk' then value = 'u_Nether Drake'
			when 'nndr' then value = 'u_Nether Dragon'

	# upgrades
	else if (value[0] == 'R')
		switch value
			when 'Rhss' then value = 'p_Control Magic'
			when 'Rhme' then value = 'p_Swords'
			when 'Rhra' then value = 'p_Gunpowder'
			when 'Rhar' then value = 'p_Plating'
			when 'Rhla' then value = 'p_Armor'
			when 'Rhac' then value = 'p_Masonry'
			when 'Rhgb' then value = 'p_Flying Machine Bombs'
			when 'Rhlh' then value = 'p_Lumber Harvesting'
			when 'Rhde' then value = 'p_Defend'
			when 'Rhan' then value = 'p_Animal War Training'
			when 'Rhpt' then value = 'p_Priest Training'
			when 'Rhst' then value = 'p_Sorceress Training'
			when 'Rhri' then value = 'p_Long Rifles'
			when 'Rhse' then value = 'p_Magic Sentry'
			when 'Rhfl' then value = 'p_Flare'
			when 'Rhhb' then value = 'p_Storm Hammers'
			when 'Rhrt' then value = 'p_Barrage'
			when 'Rhpm' then value = 'p_Backpack'
			when 'Rhfc' then value = 'p_Flak Cannons'
			when 'Rhfs' then value = 'p_Fragmentation Shards'
			when 'Rhcd' then value = 'p_Cloud'

			when 'Resm' then value = 'p_Strength of the Moon'
			when 'Resw' then value = 'p_Strength of the Wild'
			when 'Rema' then value = 'p_Moon Armor'
			when 'Rerh' then value = 'p_Reinforced Hides'
			when 'Reuv' then value = 'p_Ultravision'
			when 'Renb' then value = 'p_Nature\'s Blessing'
			when 'Reib' then value = 'p_Improved Bows'
			when 'Remk' then value = 'p_Marksmanship'
			when 'Resc' then value = 'p_Sentinel'
			when 'Remg' then value = 'p_Upgrade Moon Glaive'
			when 'Redt' then value = 'p_Druid of the Talon Training'
			when 'Redc' then value = 'p_Druid of the Claw Training'
			when 'Resi' then value = 'p_Abolish Magic'
			when 'Reht' then value = 'p_Hippogryph Taming'
			when 'Recb' then value = 'p_Corrosive Breath'
			when 'Repb' then value = 'p_Vorpal Blades'
			when 'Rers' then value = 'p_Resistant Skin'
			when 'Rehs' then value = 'p_Hardened Skin'
			when 'Reeb' then value = 'p_Mark of the Claw'
			when 'Reec' then value = 'p_Mark of the Talon'
			when 'Rews' then value = 'p_Well Spring'
			when 'Repm' then value = 'p_Backpack'
			when 'Roch' then value = 'p_Chaos'

			when 'Rome' then value = 'p_Melee Weapons'
			when 'Rora' then value = 'p_Ranged Weapons'
			when 'Roar' then value = 'p_Armor'
			when 'Rwdm' then value = 'p_War Drums Damage Increase'
			when 'Ropg' then value = 'p_Pillage'
			when 'Robs' then value = 'p_Berserker Strength'
			when 'Rows' then value = 'p_Pulverize'
			when 'Roen' then value = 'p_Ensnare'
			when 'Rovs' then value = 'p_Envenomed Spears'
			when 'Rowd' then value = 'p_Witch Doctor Training'
			when 'Rost' then value = 'p_Shaman Training'
			when 'Rosp' then value = 'p_Spiked Barricades'
			when 'Rotr' then value = 'p_Troll Regeneration'
			when 'Rolf' then value = 'p_Liquid Fire'
			when 'Ropm' then value = 'p_Backpack'
			when 'Rowt' then value = 'p_Spirit Walker Training'
			when 'Robk' then value = 'p_Berserker Upgrade'
			when 'Rorb' then value = 'p_Reinforced Defenses'
			when 'Robf' then value = 'p_Burning Oil'

			when 'Rusp' then value = 'p_Destroyer Form'
			when 'Rume' then value = 'p_Unholy Strength'
			when 'Rura' then value = 'p_Creature Attack'
			when 'Ruar' then value = 'p_Unholy Armor'
			when 'Rucr' then value = 'p_Creature Carapace'
			when 'Ruac' then value = 'p_Cannibalize'
			when 'Rugf' then value = 'p_Ghoul Frenzy'
			when 'Ruwb' then value = 'p_Web'
			when 'Rusf' then value = 'p_Stone Form'
			when 'Rune' then value = 'p_Necromancer Training'
			when 'Ruba' then value = 'p_Banshee Training'
			when 'Rufb' then value = 'p_Freezing Breath'
			when 'Rusl' then value = 'p_Skeletal Longevity'
			when 'Rupc' then value = 'p_Disease Cloud'
			when 'Rusm' then value = 'p_Skeletal Mastery'
			when 'Rubu' then value = 'p_Burrow'
			when 'Ruex' then value = 'p_Exhume Corpses'
			when 'Rupm' then value = 'p_Backpack'

	# items
	if (value[1] != '_')
		switch value
			when 'amrc' then value = 'i_Amulet of Recall'
			when 'ankh' then value = 'i_Ankh of Reincarnation'
			when 'belv' then value = 'i_Boots of Quel\'Thalas +6'
			when 'bgst' then value = 'i_Belt of Giant Strength +6'
			when 'bspd' then value = 'i_Boots of Speed'
			when 'ccmd' then value = 'i_Scepter of Mastery'
			when 'ciri' then value = 'i_Robe of the Magi +6'
			when 'ckng' then value = 'i_Crown of Kings +5'
			when 'clsd' then value = 'i_Cloak of Shadows'
			when 'crys' then value = 'i_Crystal Ball'
			when 'desc' then value = 'i_Kelen\'s Dagger of Escape'
			when 'gemt' then value = 'i_Gem of True Seeing'
			when 'gobm' then value = 'i_Goblin Land Mines'
			when 'gsou' then value = 'i_Soul Gem'
			when 'guvi' then value = 'i_Glyph of Ultravision'
			when 'gfor' then value = 'i_Glyph of Fortification'
			when 'soul' then value = 'i_Soul'
			when 'mdpb' then value = 'i_Medusa Pebble'
			when 'rag1' then value = 'i_Slippers of Agility +3'
			when 'rat3' then value = 'i_Claws of Attack +3'
			when 'rin1' then value = 'i_Mantle of Intelligence +3'
			when 'rde1' then value = 'i_Ring of Protection +2'
			when 'rde2' then value = 'i_Ring of Protection +3'
			when 'rde3' then value = 'i_Ring of Protection +4'
			when 'rhth' then value = 'i_Khadgar\'s Gem of Health'
			when 'rst1' then value = 'i_Gauntlets of Ogre Strength +3'
			when 'ofir' then value = 'i_Orb of Fire'
			when 'ofro' then value = 'i_Orb of Frost'
			when 'olig' then value = 'i_Orb of Lightning'
			when 'oli2' then value = 'i_Orb of Lightning'
			when 'oven' then value = 'i_Orb of Venom'
			when 'odef' then value = 'i_Orb of Darkness'
			when 'ocor' then value = 'i_Orb of Corruption'
			when 'pdiv' then value = 'i_Potion of Divinity'
			when 'phea' then value = 'i_Potion of Healing'
			when 'pghe' then value = 'i_Potion of Greater Healing'
			when 'pinv' then value = 'i_Potion of Invisibility'
			when 'pgin' then value = 'i_Potion of Greater Invisibility'
			when 'pman' then value = 'i_Potion of Mana'
			when 'pgma' then value = 'i_Potion of Greater Mana'
			when 'pnvu' then value = 'i_Potion of Invulnerability'
			when 'pnvl' then value = 'i_Potion of Lesser Invulnerability'
			when 'pres' then value = 'i_Potion of Restoration'
			when 'pspd' then value = 'i_Potion of Speed'
			when 'rlif' then value = 'i_Ring of Regeneration'
			when 'rwiz' then value = 'i_Sobi Mask'
			when 'sfog' then value = 'i_Horn of the Clouds'
			when 'shea' then value = 'i_Scroll of Healing'
			when 'sman' then value = 'i_Scroll of Mana'
			when 'spro' then value = 'i_Scroll of Protection'
			when 'sres' then value = 'i_Scroll of Restoration'
			when 'ssil' then value = 'i_Staff of Silence'
			when 'stwp' then value = 'i_Scroll of Town Portal'
			when 'tels' then value = 'i_Goblin Night Scope'
			when 'tdex' then value = 'i_Tome of Agility'
			when 'texp' then value = 'i_Tome of Experience'
			when 'tint' then value = 'i_Tome of Intelligence'
			when 'tkno' then value = 'i_Tome of Power'
			when 'tstr' then value = 'i_Tome of Strength'
			when 'ward' then value = 'i_Warsong Battle Drums'
			when 'will' then value = 'i_Wand of Illusion'
			when 'wneg' then value = 'i_Wand of Negation'
			when 'rdis' then value = 'i_Rune of Dispel Magic'
			when 'rwat' then value = 'i_Rune of the Watcher'
			when 'fgrd' then value = 'i_Red Drake Egg'
			when 'fgrg' then value = 'i_Stone Token'
			when 'fgdg' then value = 'i_Demonic Figurine'
			when 'fgfh' then value = 'i_Spiked Collar'
			when 'fgsk' then value = 'i_Book of the Dead'
			when 'engs' then value = 'i_Enchanted Gemstone'
			when 'k3m1' then value = 'i_Mooncrystal'
			when 'modt' then value = 'i_Mask of Death'
			when 'sand' then value = 'i_Scroll of Animate Dead'
			when 'srrc' then value = 'i_Scroll of Resurrection'
			when 'sror' then value = 'i_Scroll of the Beast'
			when 'infs' then value = 'i_Inferno Stone'
			when 'shar' then value = 'i_Ice Shard'
			when 'wild' then value = 'i_Amulet of the Wild'
			when 'wswd' then value = 'i_Sentry Wards'
			when 'whwd' then value = 'i_Healing Wards'
			when 'wlsd' then value = 'i_Wand of Lightning Shield'
			when 'wcyc' then value = 'i_Wand of the Wind'
			when 'rnec' then value = 'i_Rod of Necromancy'
			when 'pams' then value = 'i_Anti-magic Potion'
			when 'clfm' then value = 'i_Cloak of Flames'
			when 'evtl' then value = 'i_Talisman of Evasion'
			when 'nspi' then value = 'i_Necklace of Spell Immunity'
			when 'lhst' then value = 'i_The Lion Horn of Stormwind'
			when 'kpin' then value = 'i_Khadgar\'s Pipe of Insight'
			when 'sbch' then value = 'i_Scourge Bone Chimes'
			when 'afac' then value = 'i_Alleria\'s Flute of Accuracy'
			when 'ajen' then value = 'i_Ancient Janggo of Endurance'
			when 'lgdh' then value = 'i_Legion Doom-Horn'
			when 'hcun' then value = 'i_Hood of Cunning'
			when 'mcou' then value = 'i_Medallion of Courage'
			when 'hval' then value = 'i_Helm of Valor'
			when 'cnob' then value = 'i_Circlet of Nobility'
			when 'prvt' then value = 'i_Periapt of Vitality'
			when 'tgxp' then value = 'i_Tome of Greater Experience'
			when 'mnst' then value = 'i_Mana Stone'
			when 'hlst' then value = 'i_Health Stone'
			when 'tpow' then value = 'i_Tome of Knowledge'
			when 'tst2' then value = 'i_Tome of Strength +2'
			when 'tin2' then value = 'i_Tome of Intelligence +2'
			when 'tdx2' then value = 'i_Tome of Agility +2'
			when 'rde0' then value = 'i_Ring of Protection +1'
			when 'rde4' then value = 'i_Ring of Protection +5'
			when 'rat6' then value = 'i_Claws of Attack +6'
			when 'rat9' then value = 'i_Claws of Attack +9'
			when 'ratc' then value = 'i_Claws of Attack +12'
			when 'ratf' then value = 'i_Claws of Attack +15'
			when 'manh' then value = 'i_Manual of Health'
			when 'pmna' then value = 'i_Pendant of Mana'
			when 'penr' then value = 'i_Pendant of Energy'
			when 'gcel' then value = 'i_Gloves of Haste'
			when 'totw' then value = 'i_Talisman of the Wild'
			when 'phlt' then value = 'i_Phat Lewt'
			when 'gopr' then value = 'i_Glyph of Purification'
			when 'ches' then value = 'i_Cheese'
			when 'mlst' then value = 'i_Maul of Strength'
			when 'rnsp' then value = 'i_Ring of Superiority'
			when 'brag' then value = 'i_Bracer of Agility'
			when 'sksh' then value = 'i_Skull Shield'
			when 'vddl' then value = 'i_Voodoo Doll'
			when 'sprn' then value = 'i_Spider Ring'
			when 'tmmt' then value = 'i_Totem of Might'
			when 'anfg' then value = 'i_Ancient Figurine'
			when 'lnrn' then value = 'i_Lion\'s Ring'
			when 'iwbr' then value = 'i_Ironwood Branch'
			when 'jdrn' then value = 'i_Jade Ring'
			when 'drph' then value = 'i_Druid Pouch'
			when 'hslv' then value = 'i_Healing Salve'
			when 'pclr' then value = 'i_Clarity Potion'
			when 'plcl' then value = 'i_Lesser Clarity Potion'
			when 'rej1' then value = 'i_Minor Replenishment Potion'
			when 'rej2' then value = 'i_Lesser Replenishment Potion'
			when 'rej3' then value = 'i_Replenishment Potion'
			when 'rej4' then value = 'i_Greater Replenishment Potion'
			when 'rej5' then value = 'i_Lesser Scroll of Replenishment '
			when 'rej6' then value = 'i_Greater Scroll of Replenishment '
			when 'sreg' then value = 'i_Scroll of Regeneration'
			when 'gold' then value = 'i_Gold Coins'
			when 'lmbr' then value = 'i_Bundle of Lumber'
			when 'fgun' then value = 'i_Flare Gun'
			when 'pomn' then value = 'i_Potion of Omniscience'
			when 'gomn' then value = 'i_Glyph of Omniscience'
			when 'wneu' then value = 'i_Wand of Neutralization'
			when 'silk' then value = 'i_Spider Silk Broach'
			when 'lure' then value = 'i_Monster Lure'
			when 'skul' then value = 'i_Sacrificial Skull'
			when 'moon' then value = 'i_Moonstone'
			when 'brac' then value = 'i_Runed Bracers'
			when 'vamp' then value = 'i_Vampiric Potion'
			when 'woms' then value = 'i_Wand of Mana Stealing'
			when 'tcas' then value = 'i_Tiny Castle'
			when 'tgrh' then value = 'i_Tiny Great Hall'
			when 'tsct' then value = 'i_Ivory Tower'
			when 'wshs' then value = 'i_Wand of Shadowsight'
			when 'tret' then value = 'i_Tome of Retraining'
			when 'sneg' then value = 'i_Staff of Negation'
			when 'stel' then value = 'i_Staff of Teleportation'
			when 'spre' then value = 'i_Staff of Preservation'
			when 'mcri' then value = 'i_Mechanical Critter'
			when 'spsh' then value = 'i_Amulet of Spell Shield'
			when 'sbok' then value = 'i_Spell Book'
			when 'ssan' then value = 'i_Staff of Sanctuary'
			when 'shas' then value = 'i_Scroll of Speed'
			when 'dust' then value = 'i_Dust of Appearance'
			when 'oslo' then value = 'i_Orb of Slow'
			when 'dsum' then value = 'i_Diamond of Summoning'
			when 'sor1' then value = 'i_Shadow Orb +1'
			when 'sor2' then value = 'i_Shadow Orb +2'
			when 'sor3' then value = 'i_Shadow Orb +3'
			when 'sor4' then value = 'i_Shadow Orb +4'
			when 'sor5' then value = 'i_Shadow Orb +5'
			when 'sor6' then value = 'i_Shadow Orb +6'
			when 'sor7' then value = 'i_Shadow Orb +7'
			when 'sor8' then value = 'i_Shadow Orb +8'
			when 'sor9' then value = 'i_Shadow Orb +9'
			when 'sora' then value = 'i_Shadow Orb +10'
			when 'sorf' then value = 'i_Shadow Orb Fragment'
			when 'fwss' then value = 'i_Frost Wyrm Skull Shield'
			when 'ram1' then value = 'i_Ring of the Archmagi'
			when 'ram2' then value = 'i_Ring of the Archmagi'
			when 'ram3' then value = 'i_Ring of the Archmagi'
			when 'ram4' then value = 'i_Ring of the Archmagi'
			when 'shtm' then value = 'i_Shamanic Totem'
			when 'shwd' then value = 'i_Shimmerweed'
			when 'btst' then value = 'i_Battle Standard'
			when 'skrt' then value = 'i_Skeletal Artifact'
			when 'thle' then value = 'i_Thunder Lizard Egg'
			when 'sclp' then value = 'i_Secret Level Powerup'
			when 'gldo' then value = 'i_Orb of Kil\'jaeden'
			when 'tbsm' then value = 'i_Tiny Blacksmith'
			when 'tfar' then value = 'i_Tiny Farm'
			when 'tlum' then value = 'i_Tiny Lumber Mill'
			when 'tbar' then value = 'i_Tiny Barracks'
			when 'tbak' then value = 'i_Tiny Altar of Kings'
			when 'mgtk' then value = 'i_Magic Key Chain'
			when 'stre' then value = 'i_Staff of Reanimation'
			when 'horl' then value = 'i_Sacred Relic'
			when 'hbth' then value = 'i_Helm of Battlethirst'
			when 'blba' then value = 'i_Bladebane Armor'
			when 'rugt' then value = 'i_Runed Gauntlets'
			when 'frhg' then value = 'i_Firehand Gauntlets'
			when 'gvsm' then value = 'i_Gloves of Spell Mastery'
			when 'crdt' then value = 'i_Crown of the DeathLord'
			when 'arsc' then value = 'i_Arcane Scroll'
			when 'scul' then value = 'i_Scroll of the Unholy Legion'
			when 'tmsc' then value = 'i_Tome of Sacrifices'
			when 'dtsb' then value = 'i_Drek\'thar\'s Spellbook'
			when 'grsl' then value = 'i_Grimoire of Souls'
			when 'arsh' then value = 'i_Arcanite Shield'
			when 'shdt' then value = 'i_Shield of the DeathLord'
			when 'shhn' then value = 'i_Shield of Honor'
			when 'shen' then value = 'i_Enchanted Shield'
			when 'thdm' then value = 'i_Thunderlizard Diamond'
			when 'stpg' then value = 'i_Clockwork Penguin'
			when 'shrs' then value = 'i_Shimmerglaze Roast'
			when 'bfhr' then value = 'i_Bloodfeather\'s Heart'
			when 'cosl' then value = 'i_Celestial Orb of Souls'
			when 'shcw' then value = 'i_Shaman Claws'
			when 'srbd' then value = 'i_Searing Blade'
			when 'frgd' then value = 'i_Frostguard'
			when 'envl' then value = 'i_Enchanted Vial'
			when 'rump' then value = 'i_Rusty Mining Pick'
			when 'mort' then value = 'i_Mogrin\'s Report'
			when 'srtl' then value = 'i_Serathil'
			when 'stwa' then value = 'i_Sturdy War Axe'
			when 'klmm' then value = 'i_Killmaim'
			when 'rots' then value = 'i_Scepter of the Sea'
			when 'axas' then value = 'i_Ancestral Staff'
			when 'mnsf' then value = 'i_Mindstaff'
			when 'schl' then value = 'i_Scepter of Healing'
			when 'asbl' then value = 'i_Assassin\'s Blade'
			when 'kgal' then value = 'i_Keg of Ale'
			when 'dphe' then value = 'i_Thunder Phoenix Egg'
			when 'dkfw' then value = 'i_Keg of Thunderwater'
			when 'dthb' then value = 'i_Thunderbloom Bulb'
	
	return value

exports.buildingid = (value) ->
	# non-ASCII ItemIDs
	if (php.ord(value[0]) < 0x41 || php.ord(value[0]) > 0x7A)
		return 0
	
	switch value
		when 'halt' then value = 'Altar of Kings'
		when 'harm' then value = 'Workshop'
		when 'hars' then value = 'Arcane Sanctum'
		when 'hbar' then value = 'Barracks'
		when 'hbla' then value = 'Blacksmith'
		when 'hhou' then value = 'Farm'
		when 'hgra' then value = 'Gryphon Aviary'
		when 'hwtw' then value = 'Scout Tower'
		when 'hvlt' then value = 'Arcane Vault'
		when 'hlum' then value = 'Lumber Mill'
		when 'htow' then value = 'Town Hall'

		when 'etrp' then value = 'Ancient Protector'
		when 'etol' then value = 'Tree of Life'
		when 'edob' then value = 'Hunter\'s Hall'
		when 'eate' then value = 'Altar of Elders'
		when 'eden' then value = 'Ancient of Wonders'
		when 'eaoe' then value = 'Ancient of Lore'
		when 'eaom' then value = 'Ancient of War'
		when 'eaow' then value = 'Ancient of Wind'
		when 'edos' then value = 'Chimaera Roost'
		when 'emow' then value = 'Moon Well'

		when 'oalt' then value = 'Altar of Storms'
		when 'obar' then value = 'Barracks'
		when 'obea' then value = 'Beastiary'
		when 'ofor' then value = 'War Mill'
		when 'ogre' then value = 'Great Hall'
		when 'osld' then value = 'Spirit Lodge'
		when 'otrb' then value = 'Orc Burrow'
		when 'orbr' then value = 'Reinforced Orc Burrow'
		when 'otto' then value = 'Tauren Totem'
		when 'ovln' then value = 'Voodoo Lounge'
		when 'owtw' then value = 'Watch Tower'

		when 'uaod' then value = 'Altar of Darkness'
		when 'unpl' then value = 'Necropolis'
		when 'usep' then value = 'Crypt'
		when 'utod' then value = 'Temple of the Damned'
		when 'utom' then value = 'Tomb of Relics'
		when 'ugol' then value = 'Haunted Gold Mine'
		when 'uzig' then value = 'Ziggurat'
		when 'ubon' then value = 'Boneyard'
		when 'usap' then value = 'Sacrificial Pit'
		when 'uslh' then value = 'Slaughterhouse'
		when 'ugrv' then value = 'Graveyard'

		else value = 0
	
	return value

exports.time = (value) ->
	output = php.sprintf('%02d', parseInt(value/60000)) + ':'
	value = value % 60000
	output += php.sprintf('%02d', parseInt(value/1000))
	
	return output

exports.yesno = (value) ->
	if !value
		return 'No'
	
	return 'Yes'