// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = ['red', 'blue', 'teal', 'purple', 'yellow', 'orange', 'green', 'pink', 'gray', 'light-blue', 'dark-green', 'brown', 'observer'];

}).call(this);
