module.exports =
	'rightclick': 'Right click'
	'select': 'Select / deselect'
	'selecthotkey': 'Select group hotkey'
	'assignhotkey': 'Assign group hotkey'
	'ability': 'Use ability'
	'basic': 'Basic commands'
	'buildtrain': 'Build / train'
	'buildmenu': 'Enter build submenu'
	'heromenu': 'Enter hero\'s abilities submenu'
	'subgroup': 'Select subgroup'
	'item': 'Give item / drop item'
	'removeunit': 'Remove unit from queue'
	'esc': 'ESC pressed'